name: Build and Publish

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - name: Check if submodule has been pulled
      run: |
           cd opamp-spec/
           ls

    - name: Build Jar with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: jar
    
    - name: Extract the jar to see the contents
      run: |
           ls /tmp/opamp-java/io/opentelemetry/opamp-java/1.0.0/opamp-java-1.0.0.jar
           unzip /tmp/opamp-java/io/opentelemetry/opamp-java/1.0.0/opamp-java-1.0.0.jar

